# A skript for gravelcoins
# Idk if you have a variable resetter but idgaf
# Made by Cerial for GravelMine

variables:
	{getgc::%player%} = true

every 15 minutes:
	loop all players:
		set {_afk} to placeholder "essentials_afk" from loop-player
		if {_afk} = true:
			set {getgc::%player%} to false
		
		else:
			set {getgc::%player%} to true
			send action bar "&e+15 GravelCoins" to loop-player
